config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations'
  }

  resources :internships
  resources :documents
  resources :applications
  resources :organizations
  resources :choices
  resources :users
  resources :profiles
  resources :recommendations

  root 'main#index'

  get 'admin' => 'admin#index', as: :admin_home
  get 'admin/become/:user_id' => 'admin#become'
  get 'admin/debug' => 'admin#debug'
  get 'admin/debug/applications' => 'admin#debug_applications'
  get 'admin/stats' => 'admin#stats'
  get 'admin/fellowships(/:id)' => 'admin#fellowships', as: :fellowships_admin
  get 'admin/stipends' => 'admin#stipends', as: :stipends_admin
  get 'admin/emails/:category(/:status)' => 'admin#list_emails', as: :list_emails
  get 'admin/export/:category' => 'admin#export_applicants', as: :export_applicants

  get 'fellowships' => 'fellowships#index'
  match 'fellowships/rank' => 'fellowships#rank', as: :fellowships_rank, via: [ :get, :post ]
  post 'fellowships/rank/save' => 'fellowships#save_choices', as: :fellowships_save

  get 'stipends' => 'stipends#index'
  match 'stipends/questions' => 'stipends#questions', as: :stipends_questions, via: [ :get, :post ]

  get 'confirmed' => 'main#confirmed'
  get 'faq' => 'main#faq'
  get 'apply' => 'main#apply', as: :apply
  get 'apply/:category' => 'main#apply_to', as: :apply_to
  match 'apply/:category/statement' => 'main#statement', as: :statement, via: [ :get, :post ]
  match 'rec/:rec_code' => 'main#rec', as: :rec, via: [ :get, :post ]
  match 'profile' => 'main#profile', as: :user_profile, via: [ :get, :post ]
  match 'document' => 'main#document', as: :user_document, via: [ :get, :post ]

end

app/controllers/fellowships_controller.rb
class FellowshipsController < ApplicationController
  before_action :authenticate_user!, only: [ :rank, :save_choices ]
  before_action :get_application, only: [ :rank, :save_choices ]
  before_action :get_fellowships, only: [ :index, :rank ]
  before_action :check_fellowship_deadline, only: [ :rank, :save_choices ]

  def index
  end

  def rank
    @choices = @application.choices_for_frontend
    @num_selected = Fellowship::Application.config.fellowship.num_selected
    @num_applied = Fellowship::Application.config.fellowship.num_applied
  end

  def save_choices
    return render text: 'Your choices have already been submitted.', status: :bad_request if @application.completed? || @application.archived?

    success = @application.update_choices_from_frontend(JSON.parse(params[:json]))

    if not success
      return render text: 'There was a problem saving your preferences. Try reloading.', status: :bad_request
    end

    if params[:type] == 'submit'
      unless @application.choices_filled?
        return render text: 'You must provide all responses and rank at least one fellowship before you can submit.', status: :bad_request
      end

      @application.completed!
      flash[:notice] = 'Your fellowship preferences have been submitted!'
    end
    render nothing: true, status: :ok
  end

  private
    def check_fellowship_deadline
      check_deadline(:fellowship, :application)
    end

    def get_application
      @application = Application.get_or_create_current_application(current_user, :fellowship)
    end

    def get_fellowships
      @fellowships = Organization.where(active: true).all.order(category: :asc, name: :asc)
      @categories = Organization.category_tuples
    end
end

app/helpers/fellowships_helper.rb
module FellowshipsHelper
  def to_json(hash)
    raw(hash.to_json.gsub("'", %q(\\\')))
  end
end

app/views/fellowships/apply_to.html.erb
<%- model_class = Application -%>
<% title "#{model_class.human_attribute_name(@category)} - Application" %>

<div class="page-header">
  <h1>Your <%= model_class.human_attribute_name(@category) %> Application</h1>
  <p>There are five steps to completing your application. When all the steps below are showing <span class="label label-success">Completed</span> then you have completed your application process.</p>

  <p>
  <%= link_to application_path(@application, format: :pdf), class: "btn btn-default#{@profile_exists ? '' : ' disabled'}", data: { toggle: 'tooltip', placement: 'left' }, title: 'Snapshot of your application' do %>
    <i class="fa fa-fw fa-download" aria-hidden="true"></i> Download PDF
  <% end %>

  <%= link_to application_path(@application),
              method: :delete,
              class: "btn btn-default",
              data: {
                toggle: 'tooltip',
                placement: 'right',
                confirm: "Are you sure you want to delete your #{model_class.human_attribute_name(@category)} application?"
              },
              title: 'Delete your application' do %>
    <i class="fa fa-fw fa-trash-o" aria-hidden="true"></i> Delete
  <% end %>

  </p>
</div>

<!--
Profile
-->

<div class="row">
  <div class="col-md-2">
    <!-- status labels -->
    <%= @profile_exists ? print_status_label(:completed, 'success') : print_status_label(:incomplete, 'danger') %>
    <!-- /status labels -->
  </div>
  <div class="col-md-8">

    <div class="panel panel-<%= @profile_exists ? 'success' : 'danger' %>">
      <div class="panel-heading clearfix">
        <h3 class="panel-title">Step 1</h3>
      </div>
      <div class="panel-body">

        <p>Make sure that your profile is updated.</p>

        <!-- button -->
        <%= link_to user_profile_path(return_to: true), class: 'btn btn-lg btn-default' do %>
          <i class="fa fa-fw fa-user" aria-hidden="true"></i> Edit Profile
        <% end %>

      </div>
      <% unless @profile_exists %>
        <div class="panel-footer">Completing this step will also allow you to download a PDF copy of your application for your own reference.</div>
      <% end %>
    </div>
  </div>
</div>


<!--
Documents
-->

<div class="row">
  <div class="col-md-2">
    <!-- status labels -->
    <% if @resume_exists && @transcript_exists %>
      <%= print_status_label(:completed, 'success') %>
    <% else %>
      <%= @resume_exists ? print_status_label(:resume, 'success') : print_status_label(:resume, 'danger') %>
      <%= @transcript_exists ? print_status_label(:transcript, 'success') : print_status_label(:transcript, 'danger') %>
    <% end %>
    <!-- /status labels -->
  </div>
  <div class="col-md-8">

    <div class="panel panel-<%= @resume_exists && @transcript_exists ? 'success' : 'danger' %>">
      <div class="panel-heading clearfix">
        <h3 class="panel-title">Step 2</h3>
      </div>
      <div class="panel-body">

        <p>Upload supporting documents. This should at least include your resume and transcript, but you may also submit other relevant documents.</p>

        <!-- button -->
        <%= link_to user_document_path(return_to: true), class: 'btn btn-lg btn-default' do %>
          <i class="fa fa-fw fa-file-pdf-o" aria-hidden="true"></i> Upload Documents
        <% end %>
      </div>
    </div>
  </div>
</div>


<!--
Responses
-->

<div class="row">
  <div class="col-md-2">
    <!-- status labels -->
    <% if @personal_statement_exists && @relevant_coursework_exists %>
      <%= print_status_label(:completed, 'success') %>
    <% else %>
      <%= @personal_statement_exists ? print_status_label(:statement, 'success') : print_status_label(:statement, 'danger') %>
      <%= @relevant_coursework_exists ? print_status_label(:coursework, 'success') : print_status_label(:coursework, 'danger') %>
    <% end %>
    <!-- /status labels -->
  </div>
  <div class="col-md-8">

    <div class="panel panel-<%= @personal_statement_exists && @relevant_coursework_exists ? 'success' : 'danger' %>">
      <div class="panel-heading clearfix">
        <h3 class="panel-title">Step 3</h3>
      </div>
      <div class="panel-body">

        <p>Submit short responses to some shared questions that will be made available to all fellowships you apply to.</p>

        <!-- button -->
        <%= link_to statement_path(@category, return_to: true), class: 'btn btn-lg btn-default' do %>
          <i class="fa fa-fw fa-pencil" aria-hidden="true"></i> Short Responses
        <% end %>
      </div>
    </div>
  </div>
</div>


<!--
Preferences
-->

<div class="row">
  <div class="col-md-2">
    <!-- status labels -->
    <% if @ranking_submitted %>
      <%= print_status_label(:completed, 'success') %>
    <% else %>
      <%= @ranking_exists ? print_status_label(:not_submitted, 'warning') : print_status_label(:incomplete, 'danger') %>
    <% end %>
    <!-- /status labels -->
  </div>
  <div class="col-md-8">

    <div class="panel panel-<%= @ranking_submitted ? 'success' : @ranking_exists ? 'warning' : 'danger' %>">
      <div class="panel-heading clearfix">
        <h3 class="panel-title">Step 4</h3>
      </div>
      <div class="panel-body">

        <p>Rank your fellowship preferences and write a short response for each of your top <%= @num_applied %> choices.</p>

        <!-- button -->
        <%= link_to fellowships_rank_path(return_to: true), class: 'btn btn-lg btn-default' do %>
          <i class="fa fa-fw fa-sort-amount-desc" aria-hidden="true"></i> Rank Fellowships
        <% end %>
      </div>
      <% if !@ranking_submitted && @ranking_exists %>
        <div class="panel-footer">This step will be marked as completed only after you submit (and not just save) your preferences.</div>
      <% end %>
    </div>
  </div>
</div>


<!--
Recommendations
-->

<div class="row">
  <div class="col-md-2">
    <!-- status labels -->
    <%= @rec_exists ? print_status_label(:completed, 'success') : print_status_label(:not_received, 'danger') %>
    <!-- /status labels -->
  </div>
  <div class="col-md-8">

    <div class="panel panel-<%= @rec_exists ? 'success' : 'danger' %>">
      <div class="panel-heading clearfix">
        <h3 class="panel-title">Step 5</h3>
      </div>
      <div class="panel-body">

        <p>Get a letter of recommendation. Provide the following URL to your professor/mentor so that he/she can submit a recommendation for you:</p>

        <% if @profile_exists %>
          <div class="input-group">
            <input type="text" class="form-control" value="<%= rec_url(rec_code: @application.rec_code) %>" data-behavior="auto-select">
            <span class="input-group-btn">
              <a class="btn btn-default" href="mailto:?subject=SIG+Fellowship+-+Letter+of+Recommendation&amp;body=<%= rec_url(rec_code: @application.rec_code) %>"><i class="fa fa-fw fa-paper-plane" aria-hidden="true"></i> Email</a>
            </span>
          </div>
        <% else %>
          <p class="alert alert-danger">
            <i class="fa fa-warning"></i> You need to complete your profile first.
          </p>
        <% end %>
        

      </div>
      <% unless @rec_exists %>
        <div class="panel-footer">This step will be marked as completed when you have received a letter of recommendation.</div>
      <% end %>
    </div>
  </div>
</div>

app/views/fellowships/index.html.erb
<% title 'Explore Fellowships' %>

<div class="page-header">
  <h1>Explore Fellowships</h1>

  <div class="row">
    <div class="col-md-7">
      <p>SIG offers dozens of fully-funded public service internships every summer in a range of organizations around the world. You can find the list of this summer's fellowships below. Students from all majors and years are encouraged to apply, as the fellowships represent public service through a variety of disciplines.</p>
      <p><%= link_to "Learn more", 'https://sig.stanford.edu/fellowships/', class: 'btn btn-default' %>
      <%= link_to "Apply now!", apply_path, class: 'btn btn-primary' %></p>
    </div>
    <div class="col-md-4 col-md-offset-1">
      <div class="panel panel-default">
        <div class="panel-heading">Deadlines</div>
        <table class="table">
          <tr>
            <td>Application</td>
            <td><strong><%= print_deadline :fellowship, :application %></strong></td>
          </tr>
          <tr>
            <td>Recommendation</td>
            <td><strong><%= print_deadline :fellowship, :recommendation %></strong></td>
          </tr>
        </table>
      </div>
    </div>
  </div>

</div>

<div class="fellowship-explore">

<ul class="nav nav-tabs nav-justified" id="fellowship-tabs">
  <% @categories.each_with_index do |(category, category_name), i| %>
    <li class="<%= i == 0 ? 'active' : '' %>">
      <a href="#<%= category %>" data-toggle="tab"><%= category_name %></a>
    </li>
  <% end %>
</ul>

<div class="tab-content">
  <% @categories.each_with_index do |(category, category_name), i| %>
    <div class="row tab-pane fade in<%= i == 0 ? ' active' : '' %>" id="<%= category %>">

      <% @fellowships.select{|f| f.category == category.to_s}.each do |f| %>

        <div class="col-sm-4">
          <%= link_to f.url do %>
          <div class="panel panel-default fellowship-block clearfix">
            <div class="panel-heading">
              <div class="fellowship-block-thumb"><%= f.logo? ? image_tag(f.logo.url(:thumb)) : ''%></div>
            </div>
            <div class="panel-body">
              <div class="fellowship-block-header">
                <span class="fellowship-city"><%= "#{f.full_city}" %></span>
                <span class="fellowship-name"><%= f.name %></span>
              </div>
            </div>
          </div>
          <% end %>
        </div>

      <% end %>

    </div>
  <% end %>
</div>

</div>

<script>
$('#fellowship-tabs a').click(function (e) {
  e.preventDefault()
  $(this).tab('show')
})
</script>

app/views/fellowships/rank.html.erb
<%- model_class = Application -%>
<% title "#{model_class.human_attribute_name(:fellowship)} - Rank Choices" %>

<div id="fellowship-alerts">
</div>

<div class="page-header">
  <h1>Rank Choices</h1>
  <p>You may rank up to <strong><%= @num_selected %> fellowship choices</strong> and provide detailed response for the top <strong><%= @num_applied %> choices</strong>. The order in which your choices are arranged here is your order of preference, with <span class="badge">1</span> being the most preferred. Use the <i class="fa fa-chevron-up"></i> and <i class="fa fa-chevron-down"></i> buttons to reorder your choices.</p>

  <p>Note that your preferences and write-ups will not be saved until you click on <a class="btn btn-sm btn-default" data-action="save"><i class="fa fa-spin"></i> Save </a></p>

  <p>Once you submit your preferences, you will no longer be able to edit them. You need to submit your preferences before the deadline in order to finalize your application.</p>

  <% if @return_to %>
    <%= link_to 'Back', @return_to, class: 'btn-default btn' %>
  <% end %>
</div>

<div class="row">
  <div class="col-sm-9 col-sm-push-3">
    <div id="fellowship-form">

      <div class="selected-choices">
      </div>
      
    </div>
  </div>

  <div class="col-sm-3 col-sm-pull-9">
    <div id="fellowship-ranker">

      <div class="btn-group btn-group-top btn-group-justified" role="group">
        <a class="btn btn-default" data-action="save"><i class="hidden fa fa-spinner fa-spin"></i><span>Save</span></a>
        <a class="btn btn-primary" data-action="submit" title="Finalize your preferences"><i class="hidden fa fa-spinner fa-spin"></i><span>Submit</span></a>
      </div>

      <p>Select the fellowships you wish to rank from the categories below.</p>
      <div class="btn-group-top btn-group-vertical center-block" role="group">

        <% for category, category_name in @categories %>

          <div class="btn-group" role="group">
            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
              <%= category_name %>
            </button>
            <ul class="dropdown-menu" data-category="<%= category %>"></ul>
          </div>

        <% end %>
      </div>
    </div>

  </div>
</div>

<script>
  $(document).ready(function () {
    initRanker({
      alerts: '#fellowship-alerts',
      dropdown: '#fellowship-ranker',
      form: '#fellowship-form',
      max_selected: <%= @num_selected %>,
      max_applied: <%= @num_applied %>,
      save_url: '<%= fellowships_save_path %>',
      return_url: '<%= apply_to_path(:fellowship) %>',
      choices: <%= raw @choices.to_json.html_safe %>,
      fellowships: <%= to_json @fellowships %>,
      submitted: <%= @application.completed? %>
    })
  });
</script>

app/views/fellowships/statement.html.erb
<%- model_class = Application -%>
<% title "#{model_class.human_attribute_name(@category)} - Short Responses" %>

<div class="page-header">
    <h1>Short Responses</h1>
    <p>The responses you provide here are made available to all the fellowships that you apply to. Fellowship-specific responses should be reserved for the next step.
</div>

<%= simple_form_for(@application, url: statement_path, html: { method: :post }) do |f| %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Personal Statement</h3>
  </div>
  <div class="panel-body">
    <p>Please describe your personal interest in the SIG summer fellowship in no more than <strong>750 words</strong>. We recommend composing the personal statement in a separate document before pasting it here. Your response should address the following questions:</p>
    <ul>
      <li>Why are you interested in pursuing a SIG summer fellowship?</li>
      <li>What qualifications and experiences do you have that would contribute to this program?</li>
      <li>How could the fellowship enhance your academic and/or career plans?</li>
    </ul>
  </div>
      <%= f.input :pers_statement, label: false, input_html: { rows: 20 }%>
    <%= error_span(@application[:pers_statement]) %>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Relevant Coursework</h3>
  </div>
  <div class="panel-body">
    <p>In no more than <strong>125 words</strong>, please describe the coursework you have completed or are currently taking that you believe is relevant to any potential SIG fellowship.</p>
  </div>
  <%= f.input :rel_coursework, label: false, input_html: { rows: 5 }%>
  <%= error_span(@application[:rel_coursework]) %>
</div>

<div class="row">
  <%= f.button :submit, 'Save', :class => 'btn-primary btn btn-lg col-md-2 col-md-offset-5' %>
  <% if @return_to %>
    <%= link_to 'Back', @return_to, class: 'btn-default btn btn-lg col-md-2 col-md-offset-2' %>
  <% end %>
</div>

<% end %>