config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations'
  }

  resources :internships
  resources :documents
  resources :applications
  resources :organizations
  resources :choices
  resources :users
  resources :profiles
  resources :recommendations

  root 'main#index'

  get 'admin' => 'admin#index', as: :admin_home
  get 'admin/become/:user_id' => 'admin#become'
  get 'admin/debug' => 'admin#debug'
  get 'admin/debug/applications' => 'admin#debug_applications'
  get 'admin/stats' => 'admin#stats'
  get 'admin/fellowships(/:id)' => 'admin#fellowships', as: :fellowships_admin
  get 'admin/stipends' => 'admin#stipends', as: :stipends_admin
  get 'admin/emails/:category(/:status)' => 'admin#list_emails', as: :list_emails
  get 'admin/export/:category' => 'admin#export_applicants', as: :export_applicants

  get 'fellowships' => 'fellowships#index'
  match 'fellowships/rank' => 'fellowships#rank', as: :fellowships_rank, via: [ :get, :post ]
  post 'fellowships/rank/save' => 'fellowships#save_choices', as: :fellowships_save

  get 'stipends' => 'stipends#index'
  match 'stipends/questions' => 'stipends#questions', as: :stipends_questions, via: [ :get, :post ]

  get 'confirmed' => 'main#confirmed'
  get 'faq' => 'main#faq'
  get 'apply' => 'main#apply', as: :apply
  get 'apply/:category' => 'main#apply_to', as: :apply_to
  match 'apply/:category/statement' => 'main#statement', as: :statement, via: [ :get, :post ]
  match 'rec/:rec_code' => 'main#rec', as: :rec, via: [ :get, :post ]
  match 'profile' => 'main#profile', as: :user_profile, via: [ :get, :post ]
  match 'document' => 'main#document', as: :user_document, via: [ :get, :post ]

end

app/views/admin/debug.html.erb
<pre>
<% @app.each do |app|
  print = false
  r = []
  app.choices.each do |choice|
    if r.include? choice.rank
      # choice.delete
      print = true
    end
    r.push choice.rank
  end
  if print %>
    <%= app.user.name %>
    <%= app.id %>
    <% app.choices.order('rank').each do |choice| %>
      <%= choice.id %>  <%= choice.rank %>  <%= choice.organization.name %>  <%= choice.created_at %>
      <% end %>
    <% end %>
  <% end %>
</pre>

app/views/admin/debug_applications.html.erb
<pre>
<% @app.each do |app|
  print = false
  app.choices.each do |choice|
    if choice.statement.blank? && choice.rank < 3
      print = true
    end
  end
  if print %>
    <%= app.user.name %>
    <%= app.id %>
    <% app.choices.order('rank').each do |choice| %>
      <%= choice.id %>  <%= choice.rank %>  <%= choice.organization.name %>  <%= choice.statement %>
      <% end %>
    <% end %>
  <% end %>
</pre>

app/views/admin/fellowships.html.erb
<% title 'Review Fellowships' %>

<div class="page-header">
  <h1>Review Fellowship Applications</h1>
  <p>Select a fellowship from the dropdown menu to review. Submitted applications are in green.</p>

  <div class="btn-group">
    <% @fellowships.each do |category, fellowships| %>
      <div class="btn-group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <%= Organization.human_attribute_name(category) %>
          <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <% fellowships.each do |fellowship| %>
            <li<%= raw(' class="active"') if @fellowship and @fellowship.id == fellowship.id %>>
              <%= link_to fellowship.name, fellowships_admin_path(fellowship.id) %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</div>

<% unless @fellowship.nil? %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= @fellowship.name %></h3>
  </div>
  <table class="table">
    <tr><th>Rank</th><th>Applicant Name</th><th>Year</th><th>Major</th><th></th></tr>
    <% @choices.each do |choice| %>
      <%
        application = choice.application
        user = application.user
      %>
      <tr <%= raw(' class="success"') if application.completed? %>>
        <td><%= choice.rank + 1 %></td>
        <td><%= link_to user.name, application_path(application) %></td>
        <% profile = user.profile %>
        <td><%= if profile then profile.class_year else '' end %></td>
        <td><%= if profile then profile.majors else '' end %></td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false" title="Download PDFs" data-toggle="tooltip" data-placement="right">
              <i class="fa fa-file-pdf-o"></i>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'application', application_path(application, format: :pdf) %></li>
              <% application.recommendations.each do |rec| %>
                <li><%= link_to 'recommendation', recommendation_path(rec, format: :pdf) %></li>
              <% end %>
              <% user.documents.each do |doc| %>
                <li><%= link_to doc.category, doc.file.url %></li>
              <% end %>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
  <div class="panel-footer">
    <%= link_to "mailto:?bcc=#{@emails.join(',')}", class: 'btn btn-default' do %>
      <i class="fa fa-envelope-o"></i> Email
    <% end %>
  </div>
</div>
<% end %>

app/views/admin/index.html.erb
<% title 'Admin' %>

<div class="page-header">
  <h1>Admin Links</h1>
</div>

<h2>Fellowships</h2>
<%= link_to 'Fellowships', fellowships_admin_path, class: 'btn btn-default' %>
<%= link_to "Emails", list_emails_path(:fellowship), class: 'btn btn-default' %>
<%= link_to "Export", export_applicants_path(:fellowship, format: :xls), class: 'btn btn-default' %>

<h2>Stipends</h2>
<%= link_to 'Stipends', stipends_admin_path, class: 'btn btn-default' %>
<%= link_to "Emails", list_emails_path(:stipend), class: 'btn btn-default' %>
<%= link_to "Export", export_applicants_path(:stipend, format: :xls), class: 'btn btn-default' %>

app/views/admin/stats.html.erb
<% title 'Stats' %>

<div class="page-header">
  <h1>Application Stats</h1>
</div>

<div class="row">
  <div class="col-sm-6">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Overall</h3>
    </div>
    <table class="table">
      <tr><td>Registered Applicants</td><td><%= @applicants %></td></tr>
      <tr><td>Submitted Stipends</td><td><%= @num_completed_stipends %></td></tr>
      <tr><td>Pending Stipends</td><td><%= @num_stipends %></td></tr>
      <tr><td>Submitted Fellowships</td><td><%= @num_completed_fellowships %></td></tr>
      <tr><td>Pending Fellowships</td><td><%= @num_fellowships %></td></tr>
    </table>
  </div>
  </div>
</div>

<div class="row">
<% @fellowships.each do |category, fellowships|
  if fellowships.size == 0 then next end
  num_incompletes = 0
  num_completes = 0
%>

  <div class="col-md-12">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title"><%= Organization.human_attribute_name(category) %></h3>
    </div>

    <table class="table">
      <tr><th>Name</th><th>Incomplete</th><th>Submitted</th><th>Total</th></tr>
    <% fellowships.each do |fellowship| %>
      <tr>
        <td><%= fellowship.name %></td>
        <td><%= i = @incompletes[fellowship.id] || 0 %></td>
        <td><%= c = @completes[fellowship.id] || 0 %></td>
        <td><%= i + c %></td>
        <%
          num_completes += c
          num_incompletes += i
        %>
      </tr>
    <% end %>
    <tr class="active">
      <td>Total</td>
      <td><%= num_incompletes %></td>
      <td><%= num_completes %></td>
      <td><%= num_incompletes + num_completes %></td>
    </tr>
    </table>
  </div>
  </div>
<% end %>
</div>

app/views/admin/stipends.html.erb
<% title 'Review Stipends' %>

<div class="page-header">
  <h1>Review Stipend Applications</h1>
  <p>Submitted applications are in green.</p>
</div>

<div class="panel panel-default">
  <table class="table">
    <tr><th>Applicant Name</th><th>Year</th><th>Major</th><th></th></tr>
    <% @applications.each do |application| %>
      <%
        user = application.user
        if user.name.blank? then next end
      %>
      <tr <%= raw(' class="success"') if application.completed? %>>
        <td><%= link_to user.name, application_path(application) %></td>
        <% profile = user.profile %>
        <td><%= if profile then profile.class_year else '' end %></td>
        <td><%= if profile then profile.majors else '' end %></td>
        <td>
          <div class="btn-group">
            <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false" title="Download PDFs" data-toggle="tooltip" data-placement="right">
              <i class="fa fa-file-pdf-o"></i>
            </button>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'application', application_path(application, format: :pdf) %></li>
              <% application.recommendations.each do |rec| %>
                <li><%= link_to 'recommendation', recommendation_path(rec, format: :pdf) %></li>
              <% end %>
              <% user.documents.each do |doc| %>
                <li><%= link_to doc.category, doc.file.url %></li>
              <% end %>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </table>
</div>