config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations'
  }

  resources :internships
  resources :documents
  resources :applications
  resources :organizations
  resources :choices
  resources :users
  resources :profiles
  resources :recommendations

  root 'main#index'

  get 'admin' => 'admin#index', as: :admin_home
  get 'admin/become/:user_id' => 'admin#become'
  get 'admin/debug' => 'admin#debug'
  get 'admin/debug/applications' => 'admin#debug_applications'
  get 'admin/stats' => 'admin#stats'
  get 'admin/fellowships(/:id)' => 'admin#fellowships', as: :fellowships_admin
  get 'admin/stipends' => 'admin#stipends', as: :stipends_admin
  get 'admin/emails/:category(/:status)' => 'admin#list_emails', as: :list_emails
  get 'admin/export/:category' => 'admin#export_applicants', as: :export_applicants

  get 'fellowships' => 'fellowships#index'
  match 'fellowships/rank' => 'fellowships#rank', as: :fellowships_rank, via: [ :get, :post ]
  post 'fellowships/rank/save' => 'fellowships#save_choices', as: :fellowships_save

  get 'stipends' => 'stipends#index'
  match 'stipends/questions' => 'stipends#questions', as: :stipends_questions, via: [ :get, :post ]

  get 'confirmed' => 'main#confirmed'
  get 'faq' => 'main#faq'
  get 'apply' => 'main#apply', as: :apply
  get 'apply/:category' => 'main#apply_to', as: :apply_to
  match 'apply/:category/statement' => 'main#statement', as: :statement, via: [ :get, :post ]
  match 'rec/:rec_code' => 'main#rec', as: :rec, via: [ :get, :post ]
  match 'profile' => 'main#profile', as: :user_profile, via: [ :get, :post ]
  match 'document' => 'main#document', as: :user_document, via: [ :get, :post ]

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
  CATEGORIES = [ :other, :transcript, :resume, :insurance]
  enum category: CATEGORIES

  has_attached_file :file
  validates_attachment_content_type :file, content_type: ['application/pdf']
  validates_attachment_presence :file
  validates_attachment_size :file, less_than: 3.megabyte
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  respond_to :html

  def index
    @documents = Document.all
    respond_with(@documents)
  end

  def show
    respond_with(@document)
  end

  def new
    @document = Document.new
    respond_with(@document)
  end

  def edit
  end

  def create
    @document = Document.new(document_params)
    @document.save
    respond_with(@document)
  end

  def update
    @document.update(document_params)
    respond_with(@document)
  end

  def destroy
    if @document.user == current_user
      flash[:notice] = "#{@document.file_file_name} successfully deleted."
      @document.destroy
      redirect_to user_document_path
    else
      respond_with(@document)
    end
  end

  private
    def set_document
      @document = Document.find(params[:id])
    end

    def document_params
      params.require(:document).permit(:category, :user_id, :file)
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.number_field :category %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.category %></td>
        <td><%= document.user %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @document.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @document.user %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>