config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations'
  }

  resources :internships
  resources :documents
  resources :applications
  resources :organizations
  resources :choices
  resources :users
  resources :profiles
  resources :recommendations

  root 'main#index'

  get 'admin' => 'admin#index', as: :admin_home
  get 'admin/become/:user_id' => 'admin#become'
  get 'admin/debug' => 'admin#debug'
  get 'admin/debug/applications' => 'admin#debug_applications'
  get 'admin/stats' => 'admin#stats'
  get 'admin/fellowships(/:id)' => 'admin#fellowships', as: :fellowships_admin
  get 'admin/stipends' => 'admin#stipends', as: :stipends_admin
  get 'admin/emails/:category(/:status)' => 'admin#list_emails', as: :list_emails
  get 'admin/export/:category' => 'admin#export_applicants', as: :export_applicants

  get 'fellowships' => 'fellowships#index'
  match 'fellowships/rank' => 'fellowships#rank', as: :fellowships_rank, via: [ :get, :post ]
  post 'fellowships/rank/save' => 'fellowships#save_choices', as: :fellowships_save

  get 'stipends' => 'stipends#index'
  match 'stipends/questions' => 'stipends#questions', as: :stipends_questions, via: [ :get, :post ]

  get 'confirmed' => 'main#confirmed'
  get 'faq' => 'main#faq'
  get 'apply' => 'main#apply', as: :apply
  get 'apply/:category' => 'main#apply_to', as: :apply_to
  match 'apply/:category/statement' => 'main#statement', as: :statement, via: [ :get, :post ]
  match 'rec/:rec_code' => 'main#rec', as: :rec, via: [ :get, :post ]
  match 'profile' => 'main#profile', as: :user_profile, via: [ :get, :post ]
  match 'document' => 'main#document', as: :user_document, via: [ :get, :post ]

end

app/controllers/stipends_controller.rb
class StipendsController < ApplicationController
  before_action :authenticate_user!, only: [ :questions ]
  before_action :get_application, only: [ :questions ]

  def index
  end

  def questions
    check_deadline(:stipend, :second)

    @internship = @application.internship
    if @internship.nil?
      @internship = Internship.new
      @internship.application = @application
    end

    if params.has_key?(:internship)
      if @internship.update(internship_params)
        redirect_to session[:return_to], notice: "Internship details successfully saved."
      end
    end
  end

  private
    def get_application
      @application = Application.get_or_create_current_application(current_user, :stipend)
    end

    def internship_params
      params.require(:internship).permit(:application_id, :name, :city, :country, :supervisor_name, :supervisor_title, :supervisor_email, :supervisor_phone, :faculty_name, :at_home, :financial_aid, :unpaid, :minimum_length, :fulltime, :travel_warning, :political, :social_service, :category, :related_to, :work_scope, :relevance, :reason, :budget)
    end
end

app/helpers/stipends_helper.rb
module StipendsHelper
end

app/views/stipends/apply_to.html.erb
<%- model_class = Application -%>
<% title "#{model_class.human_attribute_name(@category)} - Application" %>

<div class="page-header">
  <h1>Your <%= model_class.human_attribute_name(@category) %> Application</h1>
  <p>There are five steps to completing your application. When all the steps below are showing <span class="label label-success">Completed</span> then you have completed your application process.</p>

  <p>
  <%= link_to application_path(@application, format: :pdf), class: "btn btn-default#{@profile_exists ? '' : ' disabled'}", data: { toggle: 'tooltip', placement: 'left' }, title: 'Snapshot of your application' do %>
    <i class="fa fa-fw fa-download" aria-hidden="true"></i> Download PDF
  <% end %>

  <%= link_to application_path(@application),
              method: :delete,
              class: "btn btn-default",
              data: {
                toggle: 'tooltip',
                placement: 'right',
                confirm: "Are you sure you want to delete your #{model_class.human_attribute_name(@category)} application?"
              },
              title: 'Delete your application' do %>
    <i class="fa fa-fw fa-trash-o" aria-hidden="true"></i> Delete
  <% end %>

  </p>
</div>

<!--
Profile
-->

<div class="row">
  <div class="col-md-2">
    <!-- status labels -->
    <%= @profile_exists ? print_status_label(:completed, 'success') : print_status_label(:incomplete, 'danger') %>
    <!-- /status labels -->
  </div>
  <div class="col-md-8">

    <div class="panel panel-<%= @profile_exists ? 'success' : 'danger' %>">
      <div class="panel-heading clearfix">
        <h3 class="panel-title">Step 1</h3>
      </div>
      <div class="panel-body">

        <p>Make sure that your profile is updated.</p>

        <!-- button -->
        <%= link_to user_profile_path(return_to: true), class: 'btn btn-lg btn-default' do %>
          <i class="fa fa-fw fa-user" aria-hidden="true"></i> Edit Profile
        <% end %>

      </div>
      <% unless @profile_exists %>
        <div class="panel-footer">Completing this step will also allow you to download a PDF copy of your application for your own reference.</div>
      <% end %>
    </div>
  </div>
</div>


<!--
Documents
-->

<div class="row">
  <div class="col-md-2">
    <!-- status labels -->
    <% if @insurance_exists && @resume_exists && @transcript_exists %>
      <%= print_status_label(:completed, 'success') %>
    <% else %>
      <%= @insurance_exists ? print_status_label(:insurance, 'success') : print_status_label(:insurance, 'danger') %>
      <%= @resume_exists ? print_status_label(:resume, 'success') : print_status_label(:resume, 'danger') %>
      <%= @transcript_exists ? print_status_label(:transcript, 'success') : print_status_label(:transcript, 'danger') %>
    <% end %>
    <!-- /status labels -->
  </div>
  <div class="col-md-8">

    <div class="panel panel-<%= @insurance_exists && @resume_exists && @transcript_exists ? 'success' : 'danger' %>">
      <div class="panel-heading clearfix">
        <h3 class="panel-title">Step 2</h3>
      </div>
      <div class="panel-body">

        <p>Upload supporting documents. This should at least include your resume, transcript, and health insurance documentation, but you may also submit other relevant documents.</p>

        <!-- button -->
        <%= link_to user_document_path(return_to: true), class: 'btn btn-lg btn-default' do %>
          <i class="fa fa-fw fa-file-pdf-o" aria-hidden="true"></i> Upload Documents
        <% end %>
      </div>
    </div>
  </div>
</div>

<!--
Internship
-->

<div class="row">
  <div class="col-md-2">
    <!-- status labels -->
    <%= @internship_exists ? print_status_label(:completed, 'success') : print_status_label(:incomplete, 'danger') %>
    <!-- /status labels -->
  </div>
  <div class="col-md-8">

    <div class="panel panel-<%= @internship_exists ? 'success' : 'danger' %>">
      <div class="panel-heading clearfix">
        <h3 class="panel-title">Step 3</h3>
      </div>
      <div class="panel-body">

        <p>Fill in the details for your internship.</p>

        <!-- button -->
        <%= link_to stipends_questions_path(return_to: true), class: 'btn btn-lg btn-default' do %>
          <i class="fa fa-fw fa-check-square-o" aria-hidden="true"></i> Internship Details
        <% end %>
      </div>
    </div>
  </div>
</div>

<!--
Essay
-->

<div class="row">
  <div class="col-md-2">
    <!-- status labels -->
    <% if @personal_statement_exists && @relevant_coursework_exists %>
      <%= print_status_label(:completed, 'success') %>
    <% else %>
      <%= @personal_statement_exists ? print_status_label(:essay, 'success') : print_status_label(:essay, 'danger') %>
      <%= @relevant_coursework_exists ? print_status_label(:coursework, 'success') : print_status_label(:coursework, 'danger') %>
    <% end %>
    <!-- /status labels -->
  </div>
  <div class="col-md-8">

    <div class="panel panel-<%= @personal_statement_exists && @relevant_coursework_exists ? 'success' : 'danger' %>">
      <div class="panel-heading clearfix">
        <h3 class="panel-title">Step 4</h3>
      </div>
      <div class="panel-body">

        <p>Submit your short essay response and list your relevant coursework.</p>

        <!-- button -->
        <% if @internship_exists %>
          <%= link_to statement_path(@category, return_to: true), class: 'btn btn-lg btn-default' do %>
            <i class="fa fa-fw fa-pencil" aria-hidden="true"></i> Short Essay
          <% end %>
        <% else %>
          <p class="alert alert-danger">
            <i class="fa fa-warning"></i> You need to complete Step 3 first.
          </p>
        <% end %>
        
      </div>

      <% unless @completed %>
        <div class="panel-footer">Completing this step will mark your application as submitted for review. Your supervisor can fill in the questionnaire in Step 5 at a later time.</div>
      <% end %>

    </div>
  </div>
</div>

<!--
Questionnaire
-->

<div class="row">
  <div class="col-md-2">
    <!-- status labels -->
    <%= @rec_exists ? print_status_label(:completed, 'success') : print_status_label(:not_received, 'danger') %>
    <!-- /status labels -->
  </div>
  <div class="col-md-8">

    <div class="panel panel-<%= @rec_exists ? 'success' : 'danger' %>">
      <div class="panel-heading clearfix">
        <h3 class="panel-title">Step 5</h3>
      </div>
      <div class="panel-body">

        <p>Your supervisor from the host organization must provide a written response to a short questionnaire regarding the internship. Provide the following URL to your supervisor so that they can submit their responses:</p>

        <% if @profile_exists %>
          <div class="input-group">
            <input type="text" class="form-control" value="<%= rec_url(rec_code: @application.rec_code) %>" data-behavior="auto-select">
            <span class="input-group-btn">
              <a class="btn btn-default" href="mailto:?subject=SIG+Stipend+-+Short+Questionaire&amp;body=<%= rec_url(rec_code: @application.rec_code) %>"><i class="fa fa-fw fa-paper-plane" aria-hidden="true"></i> Email</a>
            </span>
          </div>
        <% else %>
          <p class="alert alert-danger">
            <i class="fa fa-warning"></i> You need to complete your profile first.
          </p>
        <% end %>
        

      </div>
      <% unless @rec_exists %>
        <div class="panel-footer">This step will be marked as completed when your supervisor has completed the questionnaire.</div>
      <% end %>
    </div>
  </div>
</div>

app/views/stipends/index.html.erb
<% title 'Stipends' %>

<div class="page-header">
  <h1>Summer Stipends</h1>


  <div class="row">
    <div class="col-md-7">
      <p>The Stanford in Government (SIG) Stipends program provides motivated Stanford undergraduates with funding up to $7,500 for unpaid summer policy internships. Since a majority of internships in the fields of policy and government are unpaid, the Stipends Program seeks to encourage students who would otherwise be unable to pursue unpaid policy internships–e.g. students on financial aid and underclassmen–to engage with public policy, public service, and government by making these professional opportunities more accessible.</p>

      <p><%= link_to "Learn more", 'https://sig.stanford.edu/sig-stipends-program/', class: 'btn btn-default' %>
      <%= link_to "Apply now!", apply_path, class: 'btn btn-primary' %></p>
    </div>
    <div class="col-md-4 col-md-offset-1">
      <div class="panel panel-default">
        <div class="panel-heading">Deadlines</div>
        <table class="table">
          <tr>
            <td>1st Round</td>
            <td><strong><%= print_deadline :stipend, :first %></strong></td>
          </tr>
          <tr>
            <td>2nd Round</td>
            <td><strong><%= print_deadline :stipend, :second %></strong></td>
          </tr>
        </table>
      </div>
    </div>
  </div>

</div>
  

app/views/stipends/questions.html.erb
<%- model_class = Application -%>
<% title "#{model_class.human_attribute_name(:stipend)} - Internship" %>

<div class="page-header">
  <h1>Internship</h1>
  <p>Please answer the following questions about the internship that the stipend will be used on.</p>
</div>

<%= simple_form_for(@internship, url: stipends_questions_path, html: { method: :post }) do |f| %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Internship Details</h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
      <%= f.input :name, label: 'organization name', placeholder: 'Department of State, East Asian and Pacific Affairs'%>
      <%= error_span(@internship[:name]) %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-offset-2 col-md-4">
      <%= f.input :city, label: 'city', placeholder: 'Washington, DC' %>
      <%= error_span(@internship[:city]) %>
      </div>
      <div class="col-md-4">
      <%= f.input :country, label: 'country', priority: [ "United States" ] %>
      <%= error_span(@internship[:country]) %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <%= f.input :faculty_name, label: 'faculty name', placeholder: 'Dr. Albert Einstein' %>
        <p class="help-block">Name of faculty member in the broader field of my internship with whom I could meet prior to my internship for advice on my learning goals if I am awarded the stipend.</p>
        <%= error_span(@internship[:faculty_name]) %>
      </div>
    </div>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Supervisor</h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-6">
      <%= f.input :supervisor_name, label: 'full name', placeholder: 'John Smith'%>
      <%= error_span(@internship[:supervisor_name]) %>
      </div>
      <div class="col-md-6">
      <%= f.input :supervisor_title, label: 'title', placeholder: 'Deputy Section Chief'%>
      <%= error_span(@internship[:supervisor_title]) %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
      <%= f.input :supervisor_email, as: :email, label: 'email', placeholder: 'smith@state.gov' %>
      <%= error_span(@internship[:supervisor_email]) %>
      </div>
      <div class="col-md-6">
      <%= f.input :supervisor_phone, as: :tel, label: 'phone', placeholder: '+1-202-555-0105' %>
      <%= error_span(@internship[:supervisor_phone]) %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 help-block">Your supervisor will be expected to submit an internship questionnaire to Stanford in Government by the Stipends application deadline (<%= print_deadline :stipend, :first %> for first round or <%= print_deadline :stipend, :second %> for second round).</div>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Survey</h3>

  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
      <% Internship::SURVEY_LABELS.each do |key, value| %>
        <%= f.input key, as: :radio_buttons, label: value %>
        <%= error_span(@internship[key]) %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Requirements Check List</h3>

  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
      <p class="help-block">Check each box if the associated statement is true.</p>
      <% Internship::CHECK_LIST_LABELS.each do |key, value| %>
        <%= f.input key, label: value %>
        <%= error_span(@internship[key]) %>
      <% end %>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Internship Type</h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-offset-2 col-md-8">
        <p>What kind of organization is the internship with?</p>
        <p class="help-block">Please either select an option from the list provided or type in the text box if none of the options apply.</p>
        
        <div class="form-group" data-action="combo-box">
          
          <div class="row">
            <div class="col-xs-9">
              <%= f.input :category, label: false %>
              <%= error_span(@internship[:category]) %>
            </div>

            <div class="col-xs-3">
              <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
                  Select <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right" role="menu">
                  <% Internship::CATEGORIES.each do |value| %>
                    <li role="presentation"><a class="combobox-menuitem" role="menuitem" tabindex="-1"><%= value %></a></li>
                  <% end %>
                </ul>
              </div>
            </div>

        </div>
        
      </div>
    </div>
    </div>
    <div class="row">
      <div class="col-md-offset-2 col-md-8">      
        <p>What kind of work is the internship related to?</p>
        <p class="help-block">Please either select an option from the list provided or type in the text box if none of the options apply.</p>

        <div class="form-group" data-action="combo-box">
          
          <div class="row">
            <div class="col-xs-9">
              <%= f.input :related_to, label: false %>
              <%= error_span(@internship[:related_to]) %>
            </div>

            <div class="col-xs-3">
              <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-expanded="true">
                  Select <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="dropdownMenu1">
                  <% Internship::RELATED_TO.each do |value| %>
                    <li role="presentation"><a class="combobox-menuitem" role="menuitem" tabindex="-1"><%= value %></a></li>
                  <% end %>
                </ul>
              </div>
            </div>

        </div>
          
      </div>
     
    </div>
  </div>
  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Short Answer Questions</h3>
  </div>
  <div class="panel-body">
    <% Internship::SHORT_ANSWER_QUESTIONS.each do |key, value| %>
      <div class="row">
        <div class="col-md-12">
          <p><%= value %></p>
          <%= f.input key, label: false, input_html: { data: { behavior: :'auto-expand' }, rows: 4 } %>
          <%= error_span(@internship[key]) %>
        </div>
      </div>
    <% end %>

  </div>
</div>

<div class="row">
  <%= f.button :submit, 'Save', class: 'btn-primary btn btn-lg col-md-2 col-md-offset-5' %>  
  <% if @return_to %>
    <%= link_to 'Back', @return_to, class: 'btn-default btn btn-lg col-md-2 col-md-offset-2' %>
  <% end %>
</div>

<% end %>

app/views/stipends/rec.html.erb
<% title "#{Application.human_attribute_name(@application.category)} - Internship Questionnaire" %>

<div class="page-header">
  <h1>Internship Questionnaire</h1>
  <p>You are submitting an internship questionnaire for a student applying to the <%= Application.human_attribute_name(@application.category) %> program. Please answer the following short questions so that we can have a better understanding of the internship that the student is being considered for.</p>
</div>


<%= simple_form_for(@rec, url: rec_path(@application.rec_code), html: { class: 'rec-form', method: :post }) do |f| %>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <p>First, please ensure that the student name shown belong is correct.</p>
      <div class="student-name well"><%= @application.user.name %></div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <p>Please provide general information about your organization, including its mission, when the organization was founded, and current number of staff.</p>

      <div class="form-group">
      <%= text_area_tag :recommendation_general, nil, class: 'form-control', data: { behavior: :'auto-expand' }, rows: 4, name: 'recommendation[general]' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <p>Please outline the intern's job/project description. What tasks and responsibilities do you foresee offering this student during his/her nine-week, fulltime internship?</p>

      <div class="form-group">
      <%= text_area_tag :recommendation_description, nil, class: 'form-control', data: { behavior: :'auto-expand' }, rows: 4, name: 'recommendation[description]' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <p>How are the intern's specific tasks related to public policy?</p>

      <div class="form-group">
      <%= text_area_tag :recommendation_relevance, nil, class: 'form-control', data: { behavior: :'auto-expand' }, rows: 4, name: 'recommendation[relevance]' %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4 col-md-offset-2">
      <%= f.input :name, label: 'Your name', placeholder: 'John Smith'%>
      <%= error_span(@rec[:name]) %>
    </div>
    <div class="col-md-4">
      <%= f.input :email, label: 'Your email', placeholder: 'nobody@stanford.edu' %>
      <%= error_span(@rec[:email]) %>
    </div>
  </div>

  <%= f.input :text, as: :hidden %>
 
  <div class="row">
    <%= f.button :submit, 'Submit', class: 'btn-primary btn btn-lg col-md-2 col-md-offset-5' %>
  </div>

<% end %>

<script>
$(document).ready(function () {
  $('#new_recommendation').validate({
    errorClass: 'jquery-validation-error',
    errorElement: 'span',
    highlight: function(element, errorClass, validClass) {
      $(element).parent().addClass('has-error');
    },
    unhighlight: function(element, errorClass, validClass) {
      $(element).parent().removeClass('has-error');
    },
    rules: {
      'recommendation[general]': { required: true },
      'recommendation[description]': { required: true },
      'recommendation[relevance]': { required: true },
      'recommendation[name]': { required: true },
      'recommendation[email]': { required: true, email: true }
    }
  });

  $('#recommendation_general, #recommendation_relevance, #recommendation_description').change(function () {
    var text = 'GENERAL\n\n' + $('#recommendation_general').val() + '\n\nDESCRIPTION\n\n' + $('#recommendation_description').val() + '\n\nRELEVANCE\n\n' + $('#recommendation_relevance').val();
    $('#recommendation_text').val(text);
  });
});
</script>

app/views/stipends/statement.html.erb
<%- model_class = Application -%>
<% title "#{model_class.human_attribute_name(@category)} - Short Essay" %>

<div class="page-header">
    <h1>Short Essay</h1>
</div>

<%= simple_form_for(@application, url: statement_path, html: { method: :post }) do |f| %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Relevant Coursework and Previous Fellowship Awards</h3>
  </div>
  <div class="panel-body">
    <p>Please list any coursework you have completed or are currently taking that is relevant to public policy. In addition, please list all previous fellowship awards from Haas Center, Stanford in Government or other University departments.</p>
  </div>
  <%= f.input :rel_coursework, label: false, input_html: { rows: 10 }%>
  <%= error_span(@application[:rel_coursework]) %>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Essay Prompt</h3>
  </div>
  <div class="panel-body">
    <p>In no more than <strong>300 words</strong>, please elaborate on your reasons for choosing the summer internship for which you wish to receive a stipend. Your response should address the following questions:</p>
    <ul>
      <li>Why are you interested in policy in general or in this specific aspect of policy?</li>
      <li>How does the internship fit with your education goals?</li>
      <li>Do you have any previous experience/coursework in the field you are connecting to public policy through your internship?</li>
    </ul>
  </div>
      <%= f.input :pers_statement, label: false, input_html: { rows: 20 }%>
    <%= error_span(@application[:pers_statement]) %>
</div>

<div class="row">
  <%= f.button :submit, 'Save', :class => 'btn-primary btn btn-lg col-md-2 col-md-offset-5',
                                data: {
                                toggle: 'tooltip',
                                placement: 'right',
                                confirm: "Please note that by submitting this application, you waive your rights to inspect the contents of any letters or statements of recommendation submitted in support of your application."
                                }%>
  <% if @return_to %>
    <%= link_to 'Back', @return_to, class: 'btn-default btn btn-lg col-md-2 col-md-offset-2' %>
  <% end %>
</div>

<% end %>